# Example! Use 'hosts.yml' property to define this confguration.
#
# hosts:
#    - name: SSW
#      addr:
#          - 127.0.1.1
#          - 198.0.1.1
#
#    - name: SBC
#      addr:
#          - 127.0.2.1
#          - 198.0.2.1
